language: r
matrix:
  include:
    - os: linux
      dist: trusty
      r: release
    - os: osx
      osx_image: xcode7.4
      r: release
  allow_failures:
    - os: osx
      osx_image: xcode6.4
      r: release
    - os: linux
      dist: trusty
      r: devel
    - os: osx
      osx_image: xcode7.4
      r: devel
    - os: linux
      dist: trusty
      r: oldrel
  fast_finish: true

sudo: false
cache: packages

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - gfortran-4.9

env:
 global:
   - RGL_USE_NULL=TRUE

after_success:
 - Rscript -e 'covr::codecov(line_exclusions = list("R/zzz.R"))'

notifications:
  email:
    on_success: change
    on_failure: change
