# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
os: linux
dist: xenial
bioc_required: true

r:
  - 3.5
  - oldrel
  - release
  - devel

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
