language: r
sudo: false
cache: packages

r:
 - oldrel
 - release
 - devel

before_install:
 - Rscript -e 'source("https://bioconductor.org/biocLite.R"); biocLite("bioDist")'

after_success:
 - Rscript -e 'covr::codecov()'