language: r
sudo: false
cache: packages

r:
 - oldrel
 - release
 - devel

bioc_packages:
 - bioDist

env:
 global:
   - RGL_USE_NULL=TRUE

after_success:
 - Rscript -e 'covr::codecov(token = "2472ece65a3d48c18ea054a4c8497174")'