language: r
sudo: false
cache: packages

r:
 - oldrel
 - release
 - devel

bioc_packages:
 - bioDist

env:
 global:
   - RGL_USE_NULL=TRUE

after_success:
 - travis_wait Rscript -e 'covr::codecov()'
 
notifications:
  email:
    on_success: change
    on_failure: change