language: r
sudo: required
cache: packages

r:
 - release
 - devel

env:
 global:
   - RGL_USE_NULL=TRUE

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get -qq update
 - sudo apt-get -qq install g++-4.9
 - Rscript -e 'update.packages(ask = FALSE)'

after_success:
 - Rscript -e 'covr::codecov(line_exclusions = list("R/zzz.R"))'

notifications:
  email:
    on_success: change
    on_failure: change
