language: r
sudo: required
cache: packages

matrix:
  include:
  - os: linux
    dist: trusty
    r: release
    before_install: |1
     mkdir ~/.R
     cat <<EOF > ~/.R/Makevars
     CC=gcc-6
     CXX=g++-6
     CXX1X=g++-6
     CXX11=g++-6
  - os: linux
    dist: trusty
    r: devel
    before_install: |1
     mkdir ~/.R
     cat <<EOF > ~/.R/Makevars
     CC=gcc-6
     CXX=g++-6
     CXX1X=g++-6
     CXX11=g++-6

env:
  global:
  - OS=$(uname -s)
  - RGL_USE_NULL=TRUE

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - gfortran-6
      - libudunits2-dev
  brew_packages:
      - udunits

after_success:
  - Rscript -e 'covr::codecov(line_exclusions = list("R/zzz.R"))'

notifications:
  email:
    on_success: change
    on_failure: change
