language: r
sudo: required
cache: packages

r:
 - release
 - devel

env:
 global:
   - RGL_USE_NULL=TRUE

before_install:
 - |
  mkdir ~/.R
  cat <<EOF > ~/.R/Makevars
  CXX1X=g++-4.9
  CXX1XSTD=-std=c++11
 - Rscript -e 'update.packages(ask = FALSE)'

after_success:
 - Rscript -e 'covr::codecov(line_exclusions = list("R/zzz.R"))'

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

notifications:
  email:
    on_success: change
    on_failure: change
