language: r
sudo: false
cache: packages

r:
 - oldrel
 - release
 - devel

env:
 global:
   - RGL_USE_NULL=TRUE
   
before_install:
 - Rscript -e 'update.packages(ask = FALSE)'

after_success:
 - travis_wait Rscript -e 'covr::codecov()'
 
notifications:
  email:
    on_success: change
    on_failure: change