// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// connectivity_matrix
NumericMatrix connectivity_matrix(NumericVector x);
RcppExport SEXP diceR_connectivity_matrix(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(connectivity_matrix(x));
    return rcpp_result_gen;
END_RCPP
}
// indicator_matrix
NumericMatrix indicator_matrix(NumericVector x);
RcppExport SEXP diceR_indicator_matrix(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(indicator_matrix(x));
    return rcpp_result_gen;
END_RCPP
}
