# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

connectivity_matrix <- function(x) {
    .Call(`_diceR_connectivity_matrix`, x)
}

indicator_matrix <- function(x) {
    .Call(`_diceR_indicator_matrix`, x)
}

